import { sections } from "./questions";
import type { Answer, DiscoveryState } from "./types";

const empty = (answer?: Answer) => {
  if (!answer) return true;
  if (Array.isArray(answer.value)) return answer.value.length === 0;
  return answer.value === "" || answer.value === false;
};

const setPath = (target: Record<string, unknown>, path: string, value: unknown) => {
  const keys = path.split(".");
  let cursor = target;
  keys.forEach((key, index) => {
    if (index === keys.length - 1) {
      cursor[key] = value;
      return;
    }
    if (!cursor[key] || typeof cursor[key] !== "object") cursor[key] = {};
    cursor = cursor[key] as Record<string, unknown>;
  });
};

export const buildHarnessJson = (state: DiscoveryState) => {
  const payload: Record<string, unknown> = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
  };

  const confirmedFacts: string[] = [];
  const inferences: string[] = [];
  const unknowns: string[] = [];

  for (const section of sections) {
    for (const question of section.questions) {
      const answer = state.answers[question.id];
      if (!answer || empty(answer)) {
        unknowns.push(question.label);
        continue;
      }

      setPath(payload, question.id, answer.value);

      const trace = `${question.label}: ${Array.isArray(answer.value) ? answer.value.join(", ") : String(answer.value)}`;
      if (answer.status === "confirmed") confirmedFacts.push(trace);
      if (answer.status === "inferred") inferences.push(trace);
      if (answer.status === "unknown") unknowns.push(trace);
    }
  }

  payload.evidence = { confirmedFacts, inferences, unknowns };
  payload.refinement = {
    mode: "refine-existing-demo",
    instruction:
      "Inspect the existing demo repository first. Preserve good work. Use this discovery to replace assumptions with confirmed client information. Research only remaining gaps and do not regenerate from scratch without a concrete reason.",
  };

  return payload;
};

export const buildMarkdown = (state: DiscoveryState) => {
  const lines = ["# Client Discovery Brief", "", "> Generated by Discovery Console.", ""];

  for (const section of sections) {
    lines.push(`## ${section.title}`, "");
    for (const question of section.questions) {
      const answer = state.answers[question.id];
      if (!answer || empty(answer)) continue;
      const value = Array.isArray(answer.value) ? answer.value.join(", ") : String(answer.value);
      lines.push(`### ${question.label}`, `Status: **${answer.status}**`, "", value, "");
    }
  }

  const json = buildHarnessJson(state);
  const evidence = json.evidence as {
    confirmedFacts: string[];
    inferences: string[];
    unknowns: string[];
  };

  lines.push("## Open gaps", "");
  if (evidence.unknowns.length === 0) {
    lines.push("- None recorded.");
  } else {
    evidence.unknowns.forEach((item) => lines.push(`- ${item}`));
  }

  return lines.join("\n");
};

export const downloadText = (filename: string, content: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
};
