import { sections } from "./questions";
import type { Answer, DiscoveryState } from "./types";

const empty = (answer?: Answer) => {
  if (!answer) return true;
  if (Array.isArray(answer.value)) return answer.value.length === 0;
  return answer.value === "" || answer.value === false;
};

const setPath = (target: Record<string, unknown>, path: string, value: unknown) => {
  const keys = path.split(".");
  let cursor = target;
  keys.forEach((key, index) => {
    if (index === keys.length - 1) {
      cursor[key] = value;
      return;
    }
    if (!cursor[key] || typeof cursor[key] !== "object") cursor[key] = {};
    cursor = cursor[key] as Record<string, unknown>;
  });
};

export const buildHarnessJson = (state: DiscoveryState) => {
  const payload: Record<string, unknown> = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
  };

  const confirmedFacts: string[] = [];
  const inferences: string[] = [];
  const unknowns: string[] = [];

  for (const section of sections) {
    if (section.id === "demoPrompt") continue;
    for (const question of section.questions) {
      const answer = state.answers[question.id];
      if (!answer || empty(answer)) {
        unknowns.push(question.label);
        continue;
      }

      setPath(payload, question.id, answer.value);

      const trace = `${question.label}: ${Array.isArray(answer.value) ? answer.value.join(", ") : String(answer.value)}`;
      if (answer.status === "confirmed") confirmedFacts.push(trace);
      if (answer.status === "inferred") inferences.push(trace);
      if (answer.status === "unknown") unknowns.push(trace);
    }
  }

  payload.evidence = { confirmedFacts, inferences, unknowns };
  payload.refinement = {
    mode: "refine-existing-demo",
    instruction:
      "Inspect the existing demo repository first. Preserve good work. Use this discovery to replace assumptions with confirmed client information. Research only remaining gaps and do not regenerate from scratch without a concrete reason.",
  };

  return payload;
};

export const buildMarkdown = (state: DiscoveryState) => {
  const lines = ["# Client Discovery Brief", "", "> Generated by Discovery Console.", ""];

  for (const section of sections) {
    if (section.id === "demoPrompt") continue;
    lines.push(`## ${section.title}`, "");
    for (const question of section.questions) {
      const answer = state.answers[question.id];
      if (!answer || empty(answer)) continue;
      const value = Array.isArray(answer.value) ? answer.value.join(", ") : String(answer.value);
      lines.push(`### ${question.label}`, `Status: **${answer.status}**`, "", value, "");
    }
  }

  const json = buildHarnessJson(state);
  const evidence = json.evidence as {
    confirmedFacts: string[];
    inferences: string[];
    unknowns: string[];
  };

  lines.push("## Open gaps", "");
  if (evidence.unknowns.length === 0) {
    lines.push("- None recorded.");
  } else {
    evidence.unknowns.forEach((item) => lines.push(`- ${item}`));
  }

  return lines.join("\n");
};

export const downloadText = (filename: string, content: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
};


const answerText = (state: DiscoveryState, id: string) => {
  const answer = state.answers[id];
  if (!answer) return "";
  if (Array.isArray(answer.value)) return answer.value.join(", ");
  return String(answer.value ?? "").trim();
};

export const buildDemoPrompt = (state: DiscoveryState) => {
  const company = answerText(state, "demo.companyName");
  const website = answerText(state, "demo.websiteUrl");
  const industry = answerText(state, "demo.industry");
  const subcategory = answerText(state, "demo.subcategory");
  const geography = answerText(state, "demo.geography");
  const publicContext = answerText(state, "demo.publicContext");
  const goal = answerText(state, "demo.demoGoal");
  const preserve = answerText(state, "demo.mustPreserve");
  const avoid = answerText(state, "demo.avoid");
  const repo = answerText(state, "demo.targetRepository");
  const extra = answerText(state, "demo.extraInstructions");

  const lines = [
    "Use the Tasteful Landings control repository in GENERATE MODE.",
    "",
    "Create a first-contact one-shot demo from public information only.",
    "This is a sales hypothesis, not a post-discovery production site.",
    "",
    "Prospect:",
    `- Company: ${company || "[research / fill from public source]"}`,
    `- Current website: ${website || "[not provided]"}`,
    `- Industry: ${industry || "[research]"}`,
    `- Subcategory: ${subcategory || "[research and resolve before designing]"}`,
    `- Geography: ${geography || "[research if locally relevant]"}`,
  ];

  if (publicContext) lines.push("", "Known public context:", publicContext);
  if (goal) lines.push("", "What this demo should prove:", goal);
  if (preserve) lines.push("", "Public identity cues worth preserving:", preserve);
  if (avoid) lines.push("", "Avoid:", avoid);
  if (repo) lines.push("", `Create the demo in a new repository named: ${repo}`);
  if (extra) lines.push("", "Extra instructions:", extra);

  lines.push(
    "",
    "Required behavior:",
    "- Follow AGENTS.md, GENERATION_CONTRACT.md, PRINCIPLES.md, RESEARCH_PROTOCOL.md, the relevant industry brief/playbook, and the efficiency harness.",
    "- Research the actual category, competitors, niche references, buyer language, trust signals, and visual conventions before implementation.",
    "- Do not invent awards, testimonials, clients, statistics, years, certifications, inventory, locations, or other proof.",
    "- Distinguish public facts from inference. If a fact is unknown, keep it neutral instead of fabricating it.",
    "- Preserve the prospect's visible identity and category culture. Do not default to SaaS/startup aesthetics.",
    "- Generate MARKET.md, COMPETITORS.md, REFERENCES.md, and DESIGN_DIRECTION.md before implementation.",
    "- Keep the technical implementation lean and deploy-ready.",
    "- The output must be a separate demo repository suitable to send to the prospect.",
    "",
    "This demo will later be refined in-place after a discovery call. Build a strong, credible hypothesis that is easy to preserve and modify rather than an over-engineered final system."
  );

  return lines.join("\n");
};
